### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by mochechan** [lyl8213/Plate_Recognition-LPRnet#5]
Epoch....... 33
Epoch 34/300, steps = 4998, train_cost = 0.000, train_ler = 0.000, val_cost = 1.423, val_ler = 0.023, time = 2.851s, learning_rate = 0.0008099999977275729
Epoch....... 34
time:0.9731936454772949
T/F: original(length) <-------> detectcted(length)
True Traceback (most recent call last):
  File "LPRtf3.py", line 454, in <module>
    train(a)
  File "LPRtf3.py", line 419, in train
    c, steps = do_batch(train_gen,val_gen)
  File "LPRtf3.py", line 406, in do_batch
    do_report(val_gen,test_num)
  File "LPRtf3.py", line 374, in do_report
    report_accuracy(dd, test_targets)
  File "LPRtf3.py", line 359, in report_accuracy
    print(hit, number, "(", len(number), ") <-------> ", detect_number, "(", len(detect_number), ")")
UnicodeEncodeError: 'ascii' codec can't encode character '\u6d59' in position 2: ordinal not in range(128)

**Comment by lyl8213** [comment]
you can try to change the coding method using "# coding=utf-8"

**Comment by Adrian-Yan16** [comment]
> you can try to change the coding method using "# coding=utf-8"

where  to  change?
